# Generated by Django 4.2.16 on 2026-02-17 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sân')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('location', models.CharField(max_length=500, verbose_name='Địa chỉ')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá giờ thường (VND)')),
                ('peak_hour_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá giờ cao điểm (VND)')),
                ('deposit_percent', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='% tiền cọc')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Đánh giá TB')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='Số lượt review')),
                ('is_active', models.BooleanField(default=True, verbose_name='Còn hoạt động?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Sân bóng',
                'verbose_name_plural': 'Sân bóng',
                'db_table': 'fields',
                'ordering': ['-avg_rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên loại sân')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Loại sân',
                'verbose_name_plural': 'Loại sân',
                'db_table': 'field_types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FieldImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='fields/', verbose_name='Ảnh sân')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Ảnh chính?')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày upload')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fields.field', verbose_name='Sân bóng')),
            ],
            options={
                'verbose_name': 'Ảnh sân',
                'verbose_name_plural': 'Ảnh sân',
                'db_table': 'field_images',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='field',
            name='field_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fields', to='fields.fieldtype', verbose_name='Loại sân'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá (VND)')),
                ('is_peak_hour', models.BooleanField(default=False, verbose_name='Giờ cao điểm?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Còn mở?')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='fields.field', verbose_name='Sân bóng')),
            ],
            options={
                'verbose_name': 'Khung giờ',
                'verbose_name_plural': 'Khung giờ',
                'db_table': 'time_slots',
                'ordering': ['start_time'],
                'unique_together': {('field', 'start_time', 'end_time')},
            },
        ),
    ]
