# Generated by Django 5.2.13 on 2026-04-13 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_field_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['-avg_rating', 'name'], 'verbose_name': 'San bong', 'verbose_name_plural': 'San bong'},
        ),
        migrations.AlterModelOptions(
            name='fieldimage',
            options={'ordering': ['order'], 'verbose_name': 'Anh san', 'verbose_name_plural': 'Anh san'},
        ),
        migrations.AlterModelOptions(
            name='fieldtype',
            options={'ordering': ['id'], 'verbose_name': 'Loai san', 'verbose_name_plural': 'Loai san'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_time'], 'verbose_name': 'Khung gio', 'verbose_name_plural': 'Khung gio'},
        ),
        migrations.AlterField(
            model_name='field',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Danh gia TB'),
        ),
        migrations.AlterField(
            model_name='field',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao'),
        ),
        migrations.AlterField(
            model_name='field',
            name='deposit_percent',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='% tien coc'),
        ),
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mo ta'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fields', to='fields.fieldtype', verbose_name='Loai san'),
        ),
        migrations.AlterField(
            model_name='field',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Con hoat dong?'),
        ),
        migrations.AlterField(
            model_name='field',
            name='location',
            field=models.CharField(max_length=500, verbose_name='Dia chi'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ten san'),
        ),
        migrations.AlterField(
            model_name='field',
            name='peak_hour_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gia gio cao diem (VND)'),
        ),
        migrations.AlterField(
            model_name='field',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gia gio thuong (VND)'),
        ),
        migrations.AlterField(
            model_name='field',
            name='total_reviews',
            field=models.IntegerField(default=0, verbose_name='So luot review'),
        ),
        migrations.AlterField(
            model_name='field',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngay cap nhat'),
        ),
        migrations.AlterField(
            model_name='fieldimage',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fields.field', verbose_name='San bong'),
        ),
        migrations.AlterField(
            model_name='fieldimage',
            name='image_url',
            field=models.ImageField(upload_to='fields/', verbose_name='Anh san'),
        ),
        migrations.AlterField(
            model_name='fieldimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Anh chinh?'),
        ),
        migrations.AlterField(
            model_name='fieldimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Thu tu'),
        ),
        migrations.AlterField(
            model_name='fieldimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngay upload'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mo ta'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ten loai san'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(verbose_name='Gio ket thuc'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='fields.field', verbose_name='San bong'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Con mo?'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_peak_hour',
            field=models.BooleanField(default=False, verbose_name='Gio cao diem?'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gia (VND)'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(verbose_name='Gio bat dau'),
        ),
    ]
