# Generated by Django 4.2.16 on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_field_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Vi do'),
        ),
        migrations.AddField(
            model_name='field',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kinh do'),
        ),
    ]
