# Generated by Django 4.2.16 on 2026-04-15 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_convert_status_enum_to_varchar'),
        ('fields', '0003_field_coordinates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['-avg_rating', 'name'], 'verbose_name': 'San bong', 'verbose_name_plural': 'San bong'},
        ),
        migrations.AlterModelOptions(
            name='fieldimage',
            options={'ordering': ['order'], 'verbose_name': 'Anh san', 'verbose_name_plural': 'Anh san'},
        ),
        migrations.AlterModelOptions(
            name='fieldtype',
            options={'ordering': ['id'], 'verbose_name': 'Loai san', 'verbose_name_plural': 'Loai san'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_time'], 'verbose_name': 'Khung gio', 'verbose_name_plural': 'Khung gio'},
        ),
        migrations.AlterField(
            model_name='field',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Danh gia TB'),
        ),
        migrations.AlterField(
            model_name='field',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao'),
        ),
        migrations.AlterField(
            model_name='field',
            name='deposit_percent',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='% tien coc'),
        ),
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mo ta'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fields', to='fields.fieldtype', verbose_name='Loai san'),
        ),
        migrations.AlterField(
            model_name='field',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Con hoat dong?'),
        ),
        migrations.AlterField(
            model_name='field',
            name='location',
            field=models.CharField(max_length=500, verbose_name='Dia chi'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ten san'),
        ),
        migrations.AlterField(
            model_name='field',
            name='peak_hour_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gia gio cao diem (VND)'),
        ),
        migrations.AlterField(
            model_name='field',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gia gio thuong (VND)'),
        ),
        migrations.AlterField(
            model_name='field',
            name='total_reviews',
            field=models.IntegerField(default=0, verbose_name='So luot review'),
        ),
        migrations.AlterField(
            model_name='field',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngay cap nhat'),
        ),
        migrations.AlterField(
            model_name='fieldimage',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fields.field', verbose_name='San bong'),
        ),
        migrations.AlterField(
            model_name='fieldimage',
            name='image_url',
            field=models.ImageField(upload_to='fields/', verbose_name='Anh san'),
        ),
        migrations.AlterField(
            model_name='fieldimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Anh chinh?'),
        ),
        migrations.AlterField(
            model_name='fieldimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Thu tu'),
        ),
        migrations.AlterField(
            model_name='fieldimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngay upload'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mo ta'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ten loai san'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(verbose_name='Gio ket thuc'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='fields.field', verbose_name='San bong'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Con mo?'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_peak_hour',
            field=models.BooleanField(default=False, verbose_name='Gio cao diem?'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gia (VND)'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(verbose_name='Gio bat dau'),
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('field_damage', 'San bi hu hong (den, co, mat san, ...)'), ('weather', 'Thoi tiet xau'), ('emergency', 'Su co khan cap'), ('equipment', 'Thiet bi hu hong'), ('safety', 'Van de an toan'), ('other', 'Khac')], max_length=20, verbose_name='Loai su co')),
                ('severity', models.CharField(choices=[('low', 'Thap - Co the tiep tuc choi'), ('medium', 'Trung binh - Nen doi san'), ('high', 'Cao - Buoc phai dung choi')], default='medium', max_length=10, verbose_name='Muc do nghiem trong')),
                ('description', models.TextField(verbose_name='Mo ta chi tiet')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='URL anh su co')),
                ('status', models.CharField(choices=[('pending', 'Cho xu ly'), ('investigating', 'Dang dieu tra'), ('resolving', 'Dang giai quyet'), ('resolved', 'Da giai quyet'), ('cancelled', 'Da huy')], default='pending', max_length=20, verbose_name='Trang thai')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Ghi chu admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngay cap nhat')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngay giai quyet')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='bookings.booking', verbose_name='Booking lien quan')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='fields.field', verbose_name='San bong')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Nguoi bao cao')),
            ],
            options={
                'verbose_name': 'Bao cao su co',
                'verbose_name_plural': 'Bao cao su co',
                'db_table': 'incident_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldSwap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_difference', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chenh lech gia (VND)')),
                ('compensation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Boi thuong (VND)')),
                ('status', models.CharField(choices=[('pending', 'Cho xac nhan'), ('searching', 'Dang tim san thay the'), ('proposed', 'Da de xuat'), ('confirmed', 'Da xac nhan'), ('completed', 'Da hoan thanh'), ('cancelled', 'Da huy'), ('failed', 'Khong the doi')], default='pending', max_length=20, verbose_name='Trang thai')),
                ('swap_reason', models.TextField(verbose_name='Ly do doi san')),
                ('customer_notified', models.BooleanField(default=False, verbose_name='Da thong bao khach?')),
                ('customer_accepted', models.BooleanField(null=True, verbose_name='Khach da chap nhan?')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Ghi chu admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngay cap nhat')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngay xac nhan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngay hoan thanh')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to='fields.incidentreport', verbose_name='Su co lien quan')),
                ('new_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_news', to='bookings.booking', verbose_name='Booking moi')),
                ('new_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_news', to='fields.field', verbose_name='San moi')),
                ('original_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_originals', to='bookings.booking', verbose_name='Booking cu')),
                ('original_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_originals', to='fields.field', verbose_name='San cu')),
            ],
            options={
                'verbose_name': 'Doi san',
                'verbose_name_plural': 'Doi san',
                'db_table': 'field_swaps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ngay bat dau')),
                ('end_date', models.DateField(verbose_name='Ngay ket thuc')),
                ('reason', models.TextField(verbose_name='Ly do')),
                ('closure_type', models.CharField(choices=[('maintenance', 'Bao tri'), ('holiday', 'Le/Tet'), ('issue', 'Su co/Sua chua'), ('weather', 'Thoi tiet xau'), ('other', 'Khac')], default='maintenance', max_length=20, verbose_name='Loai dong cua')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='fields.field', verbose_name='San bong')),
            ],
            options={
                'verbose_name': 'Ngay dong cua',
                'verbose_name_plural': 'Ngay dong cua',
                'db_table': 'field_closures',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FieldSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Thứ Hai'), (1, 'Thứ Ba'), (2, 'Thứ Tư'), (3, 'Thứ Năm'), (4, 'Thứ Sáu'), (5, 'Thứ Bảy'), (6, 'Chủ Nhật')], verbose_name='Ngay trong tuan')),
                ('is_open', models.BooleanField(default=True, verbose_name='Mo cua?')),
                ('open_time', models.TimeField(verbose_name='Gio mo cua')),
                ('close_time', models.TimeField(verbose_name='Gio dong cua')),
                ('slot_duration', models.IntegerField(default=60, verbose_name='Thoi gian moi khung (phut)')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='fields.field', verbose_name='San bong')),
            ],
            options={
                'verbose_name': 'Lich hoat dong',
                'verbose_name_plural': 'Lich hoat dong',
                'db_table': 'field_schedules',
                'ordering': ['field', 'day_of_week'],
                'unique_together': {('field', 'day_of_week')},
            },
        ),
    ]
