# Generated by Django 4.2.16 on 2026-04-15 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_convert_status_enum_to_varchar'),
        ('fields', '0003_field_coordinates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['-avg_rating', 'name'], 'verbose_name': 'Sân bóng', 'verbose_name_plural': 'Sân bóng'},
        ),
        migrations.AlterModelOptions(
            name='fieldimage',
            options={'ordering': ['order'], 'verbose_name': 'Ảnh sân', 'verbose_name_plural': 'Ảnh sân'},
        ),
        migrations.AlterModelOptions(
            name='fieldtype',
            options={'ordering': ['id'], 'verbose_name': 'Loại sân', 'verbose_name_plural': 'Loại sân'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_time'], 'verbose_name': 'Khung giờ', 'verbose_name_plural': 'Khung giờ'},
        ),
        migrations.AlterField(
            model_name='field',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Đánh giá TB'),
        ),
        migrations.AlterField(
            model_name='field',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='field',
            name='deposit_percent',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='% tiền cọc'),
        ),
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fields', to='fields.fieldtype', verbose_name='Loại sân'),
        ),
        migrations.AlterField(
            model_name='field',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Còn hoạt động?'),
        ),
        migrations.AlterField(
            model_name='field',
            name='location',
            field=models.CharField(max_length=500, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên sân'),
        ),
        migrations.AlterField(
            model_name='field',
            name='peak_hour_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá giờ cao điểm (VND)'),
        ),
        migrations.AlterField(
            model_name='field',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá giờ thường (VND)'),
        ),
        migrations.AlterField(
            model_name='field',
            name='total_reviews',
            field=models.IntegerField(default=0, verbose_name='Số lượt review'),
        ),
        migrations.AlterField(
            model_name='field',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='fieldimage',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fields.field', verbose_name='Sân bóng'),
        ),
        migrations.AlterField(
            model_name='fieldimage',
            name='image_url',
            field=models.ImageField(upload_to='fields/', verbose_name='Ảnh sân'),
        ),
        migrations.AlterField(
            model_name='fieldimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Ảnh chính?'),
        ),
        migrations.AlterField(
            model_name='fieldimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='fieldimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày upload'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tên loại sân'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(verbose_name='Giờ kết thúc'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='fields.field', verbose_name='Sân bóng'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Còn hoạt động?'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_peak_hour',
            field=models.BooleanField(default=False, verbose_name='Giờ cao điểm?'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá (VND)'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(verbose_name='Giờ bắt đầu'),
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('field_damage', 'Sân bị hư hỏng (đèn, cỏ, mặt sân, ...)'), ('weather', 'Thời tiết xấu'), ('emergency', 'Sự cố khẩn cấp'), ('equipment', 'Thiết bị hư hỏng'), ('safety', 'Vấn đề an toàn'), ('other', 'Khác')], max_length=20, verbose_name='Loại sự cố')),
                ('severity', models.CharField(choices=[('low', 'Thấp - Có thể tiếp tục chơi'), ('medium', 'Trung bình - Nên đổi sân'), ('high', 'Cao - Bắt buộc phải dừng chơi')], default='medium', max_length=10, verbose_name='Mức độ nghiêm trọng')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='URL ảnh sự cố')),
                ('status', models.CharField(choices=[('pending', 'Cho xử lý'), ('investigating', 'Đang điều tra'), ('resolving', 'Đang giải quyết'), ('resolved', 'Đã giải quyết'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Ghi chú admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày giải quyết')),
                ('booking', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='bookings.booking', verbose_name='Booking liên quan')),
                ('field', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='fields.field', verbose_name='Sân bóng')),
                ('reported_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Người báo cáo')),
            ],
            options={
                'verbose_name': 'Báo cáo sự cố',
                'verbose_name_plural': 'Báo cáo sự cố',
                'db_table': 'incident_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldSwap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_difference', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chênh lệch giá (VND)')),
                ('compensation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bồi thường (VND)')),
                ('status', models.CharField(choices=[('pending', 'Cho xác nhận'), ('searching', 'Đang tìm sân thay thế'), ('proposed', 'Đã đề xuất'), ('confirmed', 'Đã xác nhận'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy'), ('failed', 'Không thể đổi')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('swap_reason', models.TextField(verbose_name='Lý do đổi sân')),
                ('customer_notified', models.BooleanField(default=False, verbose_name='Đã thông báo khách?')),
                ('customer_accepted', models.BooleanField(null=True, verbose_name='Khách đã chấp nhận?')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Ghi chú admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xác nhận')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('incident', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to='fields.incidentreport', verbose_name='Sự cố liên quan')),
                ('new_booking', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_news', to='bookings.booking', verbose_name='Booking mới')),
                ('new_field', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_news', to='fields.field', verbose_name='Sân mới')),
                ('original_booking', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='swap_originals', to='bookings.booking', verbose_name='Booking cũ')),
                ('original_field', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='swap_originals', to='fields.field', verbose_name='Sân cũ')),
            ],
            options={
                'verbose_name': 'Đổi sân',
                'verbose_name_plural': 'Đổi sân',
                'db_table': 'field_swaps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('reason', models.TextField(verbose_name='Lý do')),
                ('closure_type', models.CharField(choices=[('maintenance', 'Bảo trì'), ('holiday', 'Lễ/Tết'), ('issue', 'Sự cố/Sửa chữa'), ('weather', 'Thời tiết xấu'), ('other', 'Khác')], default='maintenance', max_length=20, verbose_name='Loại đóng cửa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('field', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='fields.field', verbose_name='Sân bóng')),
            ],
            options={
                'verbose_name': 'Ngày đóng cửa',
                'verbose_name_plural': 'Ngày đóng cửa',
                'db_table': 'field_closures',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FieldSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Thứ Hai'), (1, 'Thứ Ba'), (2, 'Thứ Tư'), (3, 'Thứ Năm'), (4, 'Thứ Sáu'), (5, 'Thứ Bảy'), (6, 'Chủ Nhật')], verbose_name='Ngày trong tuần')),
                ('is_open', models.BooleanField(default=True, verbose_name='Mở cửa?')),
                ('open_time', models.TimeField(verbose_name='Giờ mở cửa')),
                ('close_time', models.TimeField(verbose_name='Giờ đóng cửa')),
                ('slot_duration', models.IntegerField(default=60, verbose_name='Thời gian mỗi khung (phút)')),
                ('field', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='fields.field', verbose_name='Sân bóng')),
            ],
            options={
                'verbose_name': 'Lịch hoạt động',
                'verbose_name_plural': 'Lịch hoạt động',
                'db_table': 'field_schedules',
                'ordering': ['field', 'day_of_week'],
                'unique_together': {('field', 'day_of_week')},
            },
        ),
    ]
