# Generated by Django 4.2.16 on 2026-04-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_alter_field_options_alter_fieldimage_options_and_more'),
        ('fields', '0003_field_coordinates'),
    ]

    operations = [
    ]
