# Generated by Cursor on 2026-04-16

from django.db import migrations


INCIDENT_REPORTS_SQL = """
CREATE TABLE IF NOT EXISTS `incident_reports` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `issue_type` varchar(20) NOT NULL,
  `severity` varchar(10) NOT NULL,
  `description` longtext NOT NULL,
  `photos` json NOT NULL,
  `status` varchar(20) NOT NULL,
  `admin_notes` longtext NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `resolved_at` datetime(6) NULL,
  `booking_id` bigint NOT NULL,
  `field_id` bigint NOT NULL,
  `reported_by_id` int NULL,
  PRIMARY KEY (`id`),
  KEY `incident_reports_booking_id_idx` (`booking_id`),
  KEY `incident_reports_field_id_idx` (`field_id`),
  KEY `incident_reports_reported_by_id_idx` (`reported_by_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
"""

FIELD_SWAPS_SQL = """
CREATE TABLE IF NOT EXISTS `field_swaps` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `price_difference` decimal(10,2) NOT NULL DEFAULT 0.00,
  `compensation_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `status` varchar(20) NOT NULL,
  `swap_reason` longtext NOT NULL,
  `customer_notified` bool NOT NULL DEFAULT 0,
  `customer_accepted` bool NULL,
  `admin_notes` longtext NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `confirmed_at` datetime(6) NULL,
  `completed_at` datetime(6) NULL,
  `incident_id` bigint NOT NULL,
  `new_booking_id` bigint NULL,
  `new_field_id` bigint NULL,
  `original_booking_id` bigint NOT NULL,
  `original_field_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `field_swaps_incident_id_idx` (`incident_id`),
  KEY `field_swaps_new_booking_id_idx` (`new_booking_id`),
  KEY `field_swaps_new_field_id_idx` (`new_field_id`),
  KEY `field_swaps_original_booking_id_idx` (`original_booking_id`),
  KEY `field_swaps_original_field_id_idx` (`original_field_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("fields", "0004_alter_field_options_alter_fieldimage_options_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: schema_editor.execute(INCIDENT_REPORTS_SQL)
            if schema_editor.connection.vendor == 'mysql'
            else None,
            reverse_code=lambda apps, schema_editor: schema_editor.execute("DROP TABLE IF EXISTS `incident_reports`;")
            if schema_editor.connection.vendor == 'mysql'
            else None,
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: schema_editor.execute(FIELD_SWAPS_SQL)
            if schema_editor.connection.vendor == 'mysql'
            else None,
            reverse_code=lambda apps, schema_editor: schema_editor.execute("DROP TABLE IF EXISTS `field_swaps`;")
            if schema_editor.connection.vendor == 'mysql'
            else None,
        ),
    ]

