# Generated by Django 4.2.16 on 2026-02-17 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Ngày đặt sân')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('customer_phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng tiền')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tiền đặt cọc')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='fields.field', verbose_name='Sân bóng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Người đặt')),
            ],
            options={
                'verbose_name': 'Đơn đặt sân',
                'verbose_name_plural': 'Đơn đặt sân',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_timeslots', to='bookings.booking', verbose_name='Đơn đặt')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='booking_timeslots', to='fields.timeslot', verbose_name='Khung giờ')),
            ],
            options={
                'verbose_name': 'Khung giờ đặt',
                'verbose_name_plural': 'Khung giờ đặt',
                'db_table': 'booking_timeslots',
                'unique_together': {('booking', 'timeslot')},
            },
        ),
    ]
