# Generated by Django 4.2.16 on 2026-04-06 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpponentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_skill_level', models.CharField(choices=[('beginner', 'Yếu'), ('intermediate', 'Trung bình'), ('advanced', 'Khá'), ('professional', 'Tốt'), ('any', 'Bất kỳ')], default='any', max_length=20, verbose_name='Trình độ ưa thích')),
                ('min_rating', models.FloatField(default=0.0, verbose_name='Đánh giá tối thiểu')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='Ngày ưa thích (optional)')),
                ('preferred_time_start', models.TimeField(blank=True, null=True, verbose_name='Giờ bắt đầu ưa thích (optional)')),
                ('preferred_time_end', models.TimeField(blank=True, null=True, verbose_name='Giờ kết thúc ưa thích (optional)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú / Yêu cầu đặc biệt')),
                ('status', models.CharField(choices=[('active', 'Đang tìm'), ('matched', 'Đã match'), ('cancelled', 'Đã hủy'), ('expired', 'Hết hạn')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('is_open_to_team', models.BooleanField(default=True, verbose_name='Chấp nhận được join vào đội')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Hết hạn')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fields.field', verbose_name='Sân bóng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Yêu cầu tìm đối thủ',
                'verbose_name_plural': 'Yêu cầu tìm đối thủ',
                'db_table': 'matchmaking_opponent_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchmakingMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Ngày đấu')),
                ('scheduled_time_start', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('scheduled_time_end', models.TimeField(verbose_name='Giờ kết thúc')),
                ('requester_confirmed', models.BooleanField(default=False, verbose_name='Người tìm đã xác nhận')),
                ('opponent_confirmed', models.BooleanField(default=False, verbose_name='Đối thủ đã xác nhận')),
                ('status', models.CharField(choices=[('pending_confirmation', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending_confirmation', max_length=20, verbose_name='Trạng thái')),
                ('match_result', models.CharField(blank=True, choices=[('requester_win', 'Người tìm thắng'), ('opponent_win', 'Đối thủ thắng'), ('draw', 'Hòa')], max_length=50, null=True, verbose_name='Kết quả trận đấu')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xác nhận')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fields.field', verbose_name='Sân bóng')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_opponent', to=settings.AUTH_USER_MODEL, verbose_name='Đối thủ')),
                ('opponent_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matchmaking.opponentrequest', verbose_name='Yêu cầu tìm đối thủ')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_requester', to=settings.AUTH_USER_MODEL, verbose_name='Người tìm đối thủ')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'db_table': 'matchmaking_matches',
                'ordering': ['-created_at'],
                'unique_together': {('requester', 'opponent', 'scheduled_date', 'scheduled_time_start')},
            },
        ),
    ]
