# Generated by Django 4.2.16 on 2026-04-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ho ten')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='So dien thoai')),
                ('subject', models.CharField(max_length=200, verbose_name='Chu de')),
                ('message', models.TextField(verbose_name='Noi dung')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Da xu ly')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lien he',
                'verbose_name_plural': 'Lien he',
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
