# Generated by Django 4.2.16 on 2026-04-07 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_convert_status_enum_to_varchar'),
        ('fields', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Ngay dat san')),
                ('created_team_name', models.CharField(max_length=120, verbose_name='Ten doi tao')),
                ('created_team_image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Anh doi tao')),
                ('accepted_team_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ten doi chap nhan')),
                ('accepted_team_image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Anh doi chap nhan')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chu')),
                ('status', models.CharField(choices=[('waiting_opponent', 'Cho doi chap nhan'), ('accepted_waiting_deposit', 'Da co doi chap nhan, cho thanh toan coc'), ('deposit_paid', 'Da thanh toan coc'), ('expired', 'Het han'), ('cancelled', 'Da huy')], default='waiting_opponent', max_length=40, verbose_name='Trang thai')),
                ('reserved_until', models.DateTimeField(blank=True, null=True, verbose_name='Giu cho den')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tong tien')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tien dat coc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngay cap nhat')),
                ('booking', models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_request', to='bookings.booking', verbose_name='Booking lien ket')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests', to=settings.AUTH_USER_MODEL, verbose_name='Nguoi tao')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests', to='fields.field', verbose_name='San bong')),
            ],
            options={
                'verbose_name': 'Yeu cau giao luu',
                'verbose_name_plural': 'Yeu cau giao luu',
                'db_table': 'match_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchRequestTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_timeslots', to='matches.matchrequest', verbose_name='Yeu cau giao luu')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='match_timeslots', to='fields.timeslot', verbose_name='Khung gio')),
            ],
            options={
                'verbose_name': 'Khung gio giao luu',
                'verbose_name_plural': 'Khung gio giao luu',
                'db_table': 'match_request_timeslots',
                'unique_together': {('match_request', 'timeslot')},
            },
        ),
    ]
