# Generated by Django 4.2.16 on 2026-04-07 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_convert_status_enum_to_varchar'),
        ('fields', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Ngày đặt sân')),
                ('created_team_name', models.CharField(max_length=120, verbose_name='Tên đội tạo')),
                ('created_team_image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ảnh đội tạo')),
                ('accepted_team_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Tên đội chấp nhận')),
                ('accepted_team_image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ảnh đội chấp nhận')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('waiting_opponent', 'Chờ đối thủ chấp nhận'), ('accepted_waiting_deposit', 'Đã có đối thủ chấp nhận, chờ thanh toán cọc'), ('deposit_paid', 'Đã thanh toán cọc'), ('expired', 'Hết hạn'), ('cancelled', 'Đã hủy')], default='waiting_opponent', max_length=40, verbose_name='Trạng thái')),
                ('reserved_until', models.DateTimeField(blank=True, null=True, verbose_name='Giữ cho đến')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tổng tiền')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tiền đặt cọc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('booking', models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_request', to='bookings.booking', verbose_name='Booking liên kết')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests', to='fields.field', verbose_name='Sân bóng')),
            ],
            options={
                'verbose_name': 'Yêu cầu giao lưu',
                'verbose_name_plural': 'Yêu cầu giao lưu',
                'db_table': 'match_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchRequestTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_timeslots', to='matches.matchrequest', verbose_name='êu cầu giao lưu')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='match_timeslots', to='fields.timeslot', verbose_name='Khung giờ')),
            ],
            options={
                'verbose_name': 'Khung giờ giao lưu',
                'verbose_name_plural': 'Khung giờ giao lưu',
                'db_table': 'match_request_timeslots',
                'unique_together': {('match_request', 'timeslot')},
            },
        ),
    ]
