# Generated by Django 4.2.16 on 2026-04-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_bio_userprofile_preferred_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_position',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên đội bóng'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Giới thiệu đội bóng'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Đánh giá đội bóng (0-5 sao)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'Yếu - Người mới bắt đầu'), ('intermediate', 'Trung bình - Có kinh nghiệm'), ('advanced', 'Khá - Kỹ thuật tốt'), ('professional', 'Tốt - Chuyên nghiệp')], default='beginner', max_length=20, verbose_name='Trình độ kỹ năng đội bóng'),
        ),
    ]
