# Generated by Django 4.2.16 on 2026-04-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team_image',
            field=models.ImageField(blank=True, null=True, upload_to='team-images/', verbose_name='Anh doi bong'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ten doi bong'),
        ),
    ]
