# Generated by Django 4.2.16 on 2026-04-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_add_qr_code_and_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thoi han thanh toan'),
        ),
    ]
