# Generated by Django 4.2.16 on 2026-04-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Cho thanh toan'), ('user_confirmed', 'Nguoi dung da thanh toan - cho xac nhan admin'), ('completed', 'Da thanh toan'), ('failed', 'That bai'), ('refunded', 'Da hoan tien')], default='pending', max_length=20, verbose_name='Trang thai'),
        ),
    ]
