# Generated by Django 4.2.16 on 2026-04-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ten de nhan biet QR code', max_length=100, verbose_name='Ten QR code')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Chuyen khoan ngan hang'), ('momo', 'MoMo'), ('vnpay', 'VNPay'), ('all', 'Tat ca phuong thuc')], default='all', help_text='Phuong thuc thanh toan ma QR code nay su dung', max_length=20, verbose_name='Phuong thuc thanh toan')),
                ('qr_image', models.TextField(help_text='Anh QR code duoi dang base64 data URL', verbose_name='Anh QR (base64)')),
                ('is_active', models.BooleanField(default=True, help_text='Chi su dung QR code dang active', verbose_name='Dang hoat dong')),
                ('description', models.TextField(blank=True, help_text='Thong tin them ve QR code', verbose_name='Mo ta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngay cap nhat')),
            ],
            options={
                'verbose_name': 'QR Code thanh toan',
                'verbose_name_plural': 'QR Codes thanh toan',
                'db_table': 'payment_qr_codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
